encrypt-type: 0  # 0:standard, 1:guomi
group-channel-connections-config:
  all-channel-connections:
  - group-id: 1  #group ID
    connections-str:
                    - 106.14.15.186:20202  # node listen_ip:channel_listen_port
#                    - 106.14.15.186:20203
 
channel-service:
  group-id: 1 # The specified group to which the SDK connects
  org-id: fisco # agency name

